Fix commit cd6c5df, alter backspace function
Error: user could not continue equation using a previous answer - operator buttons would not be added to displayValue

Changing displayValue from str to array fixed this issue. Code was adjusted according to this change.

Backspace function's if/else statement was removed; will now simply pop out most recent item.
This was removed because it no longer worked with an array, and seems slightly faulty. Add back later if desired